name: Android build & release

on:
  push:
    branches: [ main ]

jobs:
  flutter_test:
    name: Flutter Test and Analyse
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Setting up Java
        uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: '21'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.2'
          channel: stable

      - name: Check Flutter Version
        run: flutter --version

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Release APK [DEV]
        run: flutter build apk --no-tree-shake-icons --flavor dev --dart-define ENV=dev --dart-define SERVER_URL=${{ secrets.SERVER_URL }} --dart-define IRBS_SERVER_URL=${{ secrets.IRBS_SERVER_URL }} --dart-define SECURITY_KEY=${{ secrets.SECURITY_KEY }} --dart-define GMAP_KEY=${{ secrets.GMAP_KEY }} --dart-define GITHUB_ISSUE_TOKEN=${{ secrets.GIT_TOKEN }} --dart-define GATELOG_WEBSOCKET_URL=${{ secrets.GATELOG_WEBSOCKET_URL }} --dart-define GATELOG_SERVER_URL=${{ secrets.GATELOG_SERVER_URL }} --dart-define MODERATION_SERVER_URL=${{ secrets.MODERATION_SERVER_URL }} --dart-define EVENT_SERVER_URL=${{ secrets.EVENT_SERVER_URL }}

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-dev-debug.apk"
          tag: v1.0.${{ github.run_number }}-dev
          token: ${{ secrets.GIT_TOKEN }}
